### ISSUE TITLE
Provide findSafeInsertPos method to return the nearest position to insert a node

### ISSUE THREAD

**Issue by 5id** [eshvedai/prosemirror-utils#1]
The `safeInsert` utility provides no way to set the selection into a newly added node since it only returns a transaction with no straightforward way to identify where the node was inserted.

Exposing the logic to identify the insert position would allow consumers to do something like:
```javascript
const insertPos = findSafeInsertPos(node)(tr);
const { tr } = state;
tr.insert(insertPos, node);
tr.setSelection(Selection.findFrom(tr.doc.resolve(tr.mapping.map(insertPos)), 1, true))
dispatch(tr)
```

**Comment by eshvedai** [comment]
Released a patch with the fix. Now cursor is set inside of the inserted node if its allowed.
